export const SFX_LIST = [
  { id: 0, name: "Choir Suspense", url: "sfx/choirSuspense.mp3" },
  { id: 1, name: "Suspense2", url: "sfx/suspense2.mp3" },
  { id: 2, name: "Lightsaber2", url: "sfx/lightsaber2.mp3" },
  { id: 3, name: "Fart", url: "sfx/fart.mp3" },
  { id: 4, name: "You Suck", url: "sfx/youSuck.mp3" },
  { id: 5, name: "Say What", url: "sfx/sayWhat.mp3" },
  { id: 6, name: "Punch", url: "sfx/punch.mp3" },
  { id: 7, name: "Record Scratch2", url: "sfx/recordScratch2.mp3" },
  { id: 8, name: "Gun Reloading", url: "sfx/gunReloading.mp3" },
  { id: 9, name: "Punch2", url: "sfx/punch2.mp3" },
  { id: 10, name: "Boom Swoosh", url: "sfx/boomSwoosh.mp3" },
  { id: 11, name: "Record Scratch", url: "sfx/recordScratch.mp3" },
  { id: 12, name: "Fail2", url: "sfx/fail2.mp3" },
  { id: 13, name: "Lightsaber", url: "sfx/lightsaber.mp3" },
  { id: 14, name: "Explosion", url: "sfx/explosion.mp3" },
  { id: 15, name: "Falling", url: "sfx/falling.mp3" },
  { id: 16, name: "Fail", url: "sfx/fail.mp3" },
  { id: 17, name: "Inception", url: "sfx/inception.mp3" },
  { id: 18, name: "To Infinity", url: "sfx/toInfinity.mp3" },
  { id: 19, name: "Mgs Alert", url: "sfx/mgsAlert.mp3" },
  { id: 20, name: "Swoosh3", url: "sfx/swoosh3.mp3" },
  { id: 21, name: "Sudden Suspense", url: "sfx/suddenSuspense.mp3" },
  { id: 22, name: "Swoosh2", url: "sfx/swoosh2.mp3" },
  { id: 23, name: "X Files", url: "sfx/xFiles.mp3" },
  { id: 24, name: "Evil Laugh", url: "sfx/evilLaugh.mp3" },
  { id: 25, name: "Rubber Duck", url: "sfx/rubberDuck.mp3" },
  { id: 26, name: "I Got A Bad Feeling", url: "sfx/iGotABadFeeling.mp3" },
  { id: 27, name: "Drum Roll", url: "sfx/drumRoll.mp3" },
  { id: 28, name: "Sad Music2", url: "sfx/sadMusic2.mp3" },
  { id: 29, name: "Nope", url: "sfx/nope.mp3" },
  { id: 30, name: "Mlg Airhorn", url: "sfx/mlgAirhorn.mp3" },
  { id: 31, name: "Ding", url: "sfx/ding.mp3" },
  { id: 32, name: "Get Over Here", url: "sfx/getOverHere.mp3" },
  { id: 33, name: "Suspense", url: "sfx/suspense.mp3" },
  { id: 34, name: "Swoosh", url: "sfx/swoosh.mp3" },
  { id: 35, name: "Victory", url: "sfx/victory.mp3" },
  { id: 36, name: "Dun Dun Dunn", url: "sfx/dunDunDunn.mp3" },
  { id: 37, name: "Splat", url: "sfx/splat.mp3" },
  { id: 38, name: "Haha Nelson", url: "sfx/hahaNelson.mp3" },
  { id: 39, name: "Choir Heaven", url: "sfx/choirHeaven.mp3" },
  { id: 40, name: "Scream", url: "sfx/scream.mp3" },
  { id: 41, name: "Slip", url: "sfx/slip.mp3" },
  { id: 42, name: "Dolphin", url: "sfx/dolphin.mp3" },
  { id: 43, name: "Sad Music", url: "sfx/sadMusic.mp3" },
  { id: 44, name: "Hey What Happened", url: "sfx/heyWhatHappened.mp3" }
]